---
- name: Load var file specific to the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install ca-certificates package
  ansible.builtin.package:
    name: "{{ package_names }}"

- name: Grab and copy the CDM certificates
  tags:
    # I don't see a good way to make these tasks idempotent
    - molecule-idempotence-notest
  block:
    - name: Grab the CISA CDM certificates from S3
      amazon.aws.aws_s3:
        bucket: "{{ cdm_certificates_third_party_bucket_name }}"
        object: "{{ item }}"
        dest: /tmp/{{ item }}
        mode: get
      become: no
      delegate_to: localhost
      loop: "{{ cdm_certificates_certificate_object_names }}"

    - name: Copy the CISA CDM certificates
      ansible.builtin.copy:
        dest: "{{ certificate_dir }}"
        mode: 0400
        src: /tmp/{{ item }}
      loop: "{{ cdm_certificates_certificate_object_names }}"
      notify:
        - Update certificate trust

    - name: Delete local copy of CISA CDM certificates
      ansible.builtin.file:
        path: /tmp/{{ item }}
        state: absent
      become: no
      delegate_to: localhost
      loop: "{{ cdm_certificates_certificate_object_names }}"
